name: Deploy DataUploadPortal to Workstations
on:
  push:
    branches:
      - main

env:
  REMOTE_IP: 67.210.192.18
  REMOTE_DIR: /home/aerotract/software/DataUploadPortal

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          - { name: "Sandra", port: 1953, method: "ssh" }
          - { name: "Jack WS", port: 2593, method: "ssh" }
          - { name: "Seth WS", port: 2599, method: "scp" }
          - { name: "Amblynn", port: 5902, method: "scp" }
          - { name: "Heidi", port: 5909, method: "scp" }
          - { name: "Front Office", port: 5910, method: "scp" }
          - { name: "Intern", port: 5911, method: "scp" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys for deployment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.WS006_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.WS006_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -p ${{ matrix.targets.port }} -H ${{ env.REMOTE_IP }} >> ~/.ssh/known_hosts

      - name: Deploy updates via SCP to ${{ matrix.targets.name }}
        if: matrix.targets.method == 'scp'
        run: |
          ssh -o PasswordAuthentication=no -p ${{ matrix.targets.port }} aerotract@${{ env.REMOTE_IP }} "mkdir -p ${{ env.REMOTE_DIR }}"
          scp -o PasswordAuthentication=no -P ${{ matrix.targets.port }} -r ./* aerotract@${{ env.REMOTE_IP }}:${{ env.REMOTE_DIR }}

      - name: Deploy updates via SSH to ${{ matrix.targets.name }}
        if: matrix.targets.method == 'ssh'
        run: |
          ssh -o PasswordAuthentication=no -p ${{ matrix.targets.port }} aerotract@67.210.192.18 "cd ${{ env.REMOTE_DIR }}; git pull"

      - name: Install updates on ${{ matrix.targets.name }}
        run: |
          ssh -o PasswordAuthentication=no -p ${{ matrix.targets.port }} aerotract@${{ env.REMOTE_IP }} "python3 -m pip install --user -r ${{ env.REMOTE_DIR }}/requirements.txt"
          ssh -o PasswordAuthentication=no -p ${{ matrix.targets.port }} aerotract@${{ env.REMOTE_IP }} "cd ${{ env.REMOTE_DIR }}/desktop; ./install.sh"